type write_guard = {
  guard_path : string;
  guard_allowed : bool;
  guard_reason : string;
  guard_required_command : string;
}

let format = "protoss-agent-protocol-v1"

let commit_format = "protoss-agent-commit-v1"

let guard_format = "protoss-agent-write-guard-v1"

let factor_format = "protoss-factor-identical-v1"

let json_string_list xs = Kernel.json_array Kernel.json_string xs

let sort_uniq_strings xs = List.sort_uniq String.compare xs

let contains haystack needle =
  let haystack_len = String.length haystack and needle_len = String.length needle in
  needle_len = 0
  ||
  let rec loop i =
    i + needle_len <= haystack_len
    && (String.sub haystack i needle_len = needle || loop (i + 1))
  in
  loop 0

let has_suffix suffix s =
  let suffix_len = String.length suffix and len = String.length s in
  len >= suffix_len && String.sub s (len - suffix_len) suffix_len = suffix

let normalize_path path =
  path |> String.lowercase_ascii |> String.map (function '\\' -> '/' | c -> c)

let path_has_segment path segment = contains ("/" ^ path ^ "/") ("/" ^ segment ^ "/")

let direct_canonical_reason path =
  let path = normalize_path path in
  if has_suffix "/program.canon" path || has_suffix "/program.graph.json" path then
    Some "program canonical artifacts are written only by validated patch/project commands"
  else if has_suffix ".ptc" path || has_suffix ".ptb" path then
    Some "canonical source artifacts are generated outputs, not direct agent write targets"
  else if
    List.exists
      (path_has_segment path)
      [
        "defs";
        "objects";
        "graphs";
        "types";
        "deps";
        "normal";
        "defids";
        "capability-scopes";
        "host-contracts";
      ]
  then Some "store internals are mutated only through validated patch/project commands"
  else if path_has_segment path "provenance" || path_has_segment path "patches" then
    Some "audit and provenance records are written only by patch commit"
  else if
    List.exists
      (fun suffix -> has_suffix suffix path)
      [ "/universe.root"; "/universe.root.content"; "/host.contract.json"; "/lock"; "/package" ]
  then Some "root, lock, package, and host-contract artifacts are generated by trusted commands"
  else None

let guard_write path =
  match direct_canonical_reason path with
  | Some reason ->
      {
        guard_path = path;
        guard_allowed = false;
        guard_reason = reason;
        guard_required_command = "protoss agent commit <store> <patch.json>";
      }
  | None ->
      {
        guard_path = path;
        guard_allowed = true;
        guard_reason = "path is outside canonical/store internals";
        guard_required_command = "";
      }

let guard_write_allowed path = (guard_write path).guard_allowed

let guard_write_result_json guard =
  Kernel.json_obj
    [
      Kernel.json_field "format" (Kernel.json_string guard_format);
      Kernel.json_field "path" (Kernel.json_string guard.guard_path);
      Kernel.json_field "allowed" (Kernel.json_bool guard.guard_allowed);
      Kernel.json_field "decision"
        (Kernel.json_string (if guard.guard_allowed then "allow" else "deny"));
      Kernel.json_field "reason" (Kernel.json_string guard.guard_reason);
      Kernel.json_field "requiredCommand" (Kernel.json_string guard.guard_required_command);
    ]
  ^ "\n"

let guard_write_json path = guard_write_result_json (guard_write path)

let stage_json name input output command =
  Kernel.json_obj
    [
      Kernel.json_field "name" (Kernel.json_string name);
      Kernel.json_field "input" (Kernel.json_string input);
      Kernel.json_field "output" (Kernel.json_string output);
      Kernel.json_field "command" (Kernel.json_string command);
    ]

let protocol_json () =
  Kernel.json_obj
    [
      Kernel.json_field "format" (Kernel.json_string format);
      Kernel.json_field "pipeline"
        (json_string_list [ "AI"; "PatchCandidate"; "Validator"; "Harness"; "Commit" ]);
      Kernel.json_field "stages"
        (Kernel.json_array
           (fun (name, input, output, command) -> stage_json name input output command)
           [
             ( "AI",
               "agent intent plus graph/query context",
               "patch candidate proposal",
               "protoss agent graph / protoss agent explain" );
             ( "PatchCandidate",
               "structured patch JSON",
               "reviewable patch candidate",
               "protoss patch review <patch.json>" );
             ( "Validator",
               "patch candidate and target store",
               "checked patch or diagnostic",
               "protoss patch check <store> <patch.json>" );
             ( "Harness",
               "checked patch and attached harness set",
               "harness pass/fail report",
               "reserved: protoss harness run <store>" );
             ( "Commit",
               "validated patch and passing harness report",
               "content-addressed patch audit",
               "protoss agent commit <store> <patch.json>" );
           ]);
      Kernel.json_field "mutationPolicy"
        (Kernel.json_obj
           [
             Kernel.json_field "directCanonicalWrites" (Kernel.json_string "forbidden");
             Kernel.json_field "guardCommand"
               (Kernel.json_string "protoss agent guard-write <path>");
             Kernel.json_field "commitCommand"
               (Kernel.json_string "protoss agent commit <store> <patch.json>");
           ]);
    ]
  ^ "\n"

type factor_delete = {
  delete_name : string;
  delete_def_id : string;
  delete_representative : string;
  delete_deps : string list;
}

type factor_blocked = {
  blocked_name : string;
  blocked_def_id : string;
  blocked_representative : string;
  blocked_dependents : string list;
}

type factor_group = {
  group_def_id : string;
  group_representative : string;
  group_names : string list;
  group_deletes : factor_delete list;
  group_blocked : factor_blocked list;
}

type factor_plan = {
  factor_groups : factor_group list;
  factor_deletes : factor_delete list;
  factor_blocked : factor_blocked list;
}

let source_dependents defs name =
  defs
  |> List.filter (fun (d : Ast.def) ->
         not (String.equal d.name name)
         && List.exists (String.equal name) (Kernel.dependencies_of_defs defs d.name))
  |> List.map (fun (d : Ast.def) -> d.name)
  |> sort_uniq_strings

let duplicate_groups checked =
  let groups = Hashtbl.create (List.length checked.Kernel.defs) in
  List.iter
    (fun (d : Kernel.checked_def) ->
      let existing = Option.value (Hashtbl.find_opt groups d.Kernel.def_id) ~default:[] in
      Hashtbl.replace groups d.Kernel.def_id (d :: existing))
    checked.Kernel.defs;
  Hashtbl.fold
    (fun def_id defs acc ->
      let defs =
        List.sort
          (fun (a : Kernel.checked_def) (b : Kernel.checked_def) ->
            String.compare a.Kernel.def.name b.Kernel.def.name)
          defs
      in
      match defs with _ :: _ :: _ -> (def_id, defs) :: acc | _ -> acc)
    groups []
  |> List.sort (fun (a, _) (b, _) -> String.compare a b)

let factor_group checked (def_id, defs) =
  let source_defs = checked.Kernel.program.defs in
  let representative =
    match defs with
    | first :: _ -> first.Kernel.def.name
    | [] -> Kernel.fail "internal empty duplicate group"
  in
  let names = List.map (fun (d : Kernel.checked_def) -> d.Kernel.def.name) defs in
  let deletes, blocked =
    match defs with
    | [] | [ _ ] -> ([], [])
    | _representative :: duplicates ->
        duplicates
        |> List.fold_left
             (fun (deletes, blocked) (d : Kernel.checked_def) ->
               let dependents = source_dependents source_defs d.Kernel.def.name in
               if dependents = [] then
                 ( {
                     delete_name = d.Kernel.def.name;
                     delete_def_id = def_id;
                     delete_representative = representative;
                     delete_deps =
                       Kernel.dependencies_of_defs source_defs d.Kernel.def.name
                       |> sort_uniq_strings;
                   }
                   :: deletes,
                   blocked )
               else
                 ( deletes,
                   {
                     blocked_name = d.Kernel.def.name;
                     blocked_def_id = def_id;
                     blocked_representative = representative;
                     blocked_dependents = dependents;
                   }
                   :: blocked ))
             ([], [])
  in
  {
    group_def_id = def_id;
    group_representative = representative;
    group_names = names;
    group_deletes = List.rev deletes;
    group_blocked = List.rev blocked;
  }

let factor_identical_plan checked =
  let groups = duplicate_groups checked |> List.map (factor_group checked) in
  {
    factor_groups = groups;
    factor_deletes = List.concat_map (fun group -> group.group_deletes) groups;
    factor_blocked = List.concat_map (fun group -> group.group_blocked) groups;
  }

let factor_delete_op_json delete =
  Kernel.json_obj
    [
      Kernel.json_field "op" (Kernel.json_string "DeleteDef");
      Kernel.json_field "name" (Kernel.json_string delete.delete_name);
      Kernel.json_field "deps" (json_string_list delete.delete_deps);
    ]

let factor_patch_candidate_json plan =
  Kernel.json_obj
    [ Kernel.json_field "ops" (Kernel.json_array factor_delete_op_json plan.factor_deletes) ]

let factor_delete_json delete =
  Kernel.json_obj
    [
      Kernel.json_field "name" (Kernel.json_string delete.delete_name);
      Kernel.json_field "defId" (Kernel.json_string delete.delete_def_id);
      Kernel.json_field "representative" (Kernel.json_string delete.delete_representative);
      Kernel.json_field "deps" (json_string_list delete.delete_deps);
    ]

let factor_blocked_json blocked =
  Kernel.json_obj
    [
      Kernel.json_field "name" (Kernel.json_string blocked.blocked_name);
      Kernel.json_field "defId" (Kernel.json_string blocked.blocked_def_id);
      Kernel.json_field "representative" (Kernel.json_string blocked.blocked_representative);
      Kernel.json_field "dependents" (json_string_list blocked.blocked_dependents);
      Kernel.json_field "reason"
        (Kernel.json_string "source dependents must be rewritten before deletion");
    ]

let factor_group_json group =
  Kernel.json_obj
    [
      Kernel.json_field "defId" (Kernel.json_string group.group_def_id);
      Kernel.json_field "representative" (Kernel.json_string group.group_representative);
      Kernel.json_field "names" (json_string_list group.group_names);
      Kernel.json_field "safeDeletes" (Kernel.json_array factor_delete_json group.group_deletes);
      Kernel.json_field "blocked" (Kernel.json_array factor_blocked_json group.group_blocked);
    ]

let factor_identical_patch_json checked =
  factor_patch_candidate_json (factor_identical_plan checked) ^ "\n"

let factor_identical_json checked =
  let plan = factor_identical_plan checked in
  Kernel.json_obj
    [
      Kernel.json_field "format" (Kernel.json_string factor_format);
      Kernel.json_field "protocol" (Kernel.json_string format);
      Kernel.json_field "stage" (Kernel.json_string "PatchCandidate");
      Kernel.json_field "programHash" (Kernel.json_string (Kernel.hash_program checked));
      Kernel.json_field "duplicateGroups" (string_of_int (List.length plan.factor_groups));
      Kernel.json_field "safeDeleteCount" (string_of_int (List.length plan.factor_deletes));
      Kernel.json_field "blockedCount" (string_of_int (List.length plan.factor_blocked));
      Kernel.json_field "groups" (Kernel.json_array factor_group_json plan.factor_groups);
      Kernel.json_field "patchCandidate" (factor_patch_candidate_json plan);
      Kernel.json_field "validationCommand"
        (Kernel.json_string "protoss patch check <store> <patch.json>");
      Kernel.json_field "commitCommand"
        (Kernel.json_string "protoss agent commit <store> <patch.json>");
    ]
  ^ "\n"

let commit_patch_json store patch =
  let checked = Patch.check store patch in
  let result = Patch.describe_checked checked in
  let patch_ref = Patch.apply store patch in
  Kernel.json_obj
    [
      Kernel.json_field "format" (Kernel.json_string commit_format);
      Kernel.json_field "protocol" (Kernel.json_string format);
      Kernel.json_field "stage" (Kernel.json_string "Commit");
      Kernel.json_field "store" (Kernel.json_string store);
      Kernel.json_field "patch" (Kernel.json_string patch);
      Kernel.json_field "mutation" (Kernel.json_string "validated-patch");
      Kernel.json_field "harnessStatus" (Kernel.json_string "empty-harness-set");
      Kernel.json_field "directCanonicalWrites" (Kernel.json_bool false);
      Kernel.json_field "result" (Kernel.json_string result);
      Kernel.json_field "patchRef" (Kernel.json_string patch_ref);
      Kernel.json_field "canonicalWriteGuard"
        (String.trim (guard_write_json (Filename.concat store "program.canon")));
    ]
  ^ "\n"
