type write_guard = {
  guard_path : string;
  guard_allowed : bool;
  guard_reason : string;
  guard_required_command : string;
}

let format = "protoss-agent-protocol-v1"

let commit_format = "protoss-agent-commit-v1"

let guard_format = "protoss-agent-write-guard-v1"

let json_string_list xs = Kernel.json_array Kernel.json_string xs

let contains haystack needle =
  let haystack_len = String.length haystack and needle_len = String.length needle in
  needle_len = 0
  ||
  let rec loop i =
    i + needle_len <= haystack_len
    && (String.sub haystack i needle_len = needle || loop (i + 1))
  in
  loop 0

let has_suffix suffix s =
  let suffix_len = String.length suffix and len = String.length s in
  len >= suffix_len && String.sub s (len - suffix_len) suffix_len = suffix

let normalize_path path =
  path |> String.lowercase_ascii |> String.map (function '\\' -> '/' | c -> c)

let path_has_segment path segment = contains ("/" ^ path ^ "/") ("/" ^ segment ^ "/")

let direct_canonical_reason path =
  let path = normalize_path path in
  if has_suffix "/program.canon" path || has_suffix "/program.graph.json" path then
    Some "program canonical artifacts are written only by validated patch/project commands"
  else if has_suffix ".ptc" path || has_suffix ".ptb" path then
    Some "canonical source artifacts are generated outputs, not direct agent write targets"
  else if
    List.exists
      (path_has_segment path)
      [
        "defs";
        "objects";
        "graphs";
        "types";
        "deps";
        "normal";
        "defids";
        "capability-scopes";
        "host-contracts";
      ]
  then Some "store internals are mutated only through validated patch/project commands"
  else if path_has_segment path "provenance" || path_has_segment path "patches" then
    Some "audit and provenance records are written only by patch commit"
  else if
    List.exists
      (fun suffix -> has_suffix suffix path)
      [ "/universe.root"; "/universe.root.content"; "/host.contract.json"; "/lock"; "/package" ]
  then Some "root, lock, package, and host-contract artifacts are generated by trusted commands"
  else None

let guard_write path =
  match direct_canonical_reason path with
  | Some reason ->
      {
        guard_path = path;
        guard_allowed = false;
        guard_reason = reason;
        guard_required_command = "protoss agent commit <store> <patch.json>";
      }
  | None ->
      {
        guard_path = path;
        guard_allowed = true;
        guard_reason = "path is outside canonical/store internals";
        guard_required_command = "";
      }

let guard_write_allowed path = (guard_write path).guard_allowed

let guard_write_result_json guard =
  Kernel.json_obj
    [
      Kernel.json_field "format" (Kernel.json_string guard_format);
      Kernel.json_field "path" (Kernel.json_string guard.guard_path);
      Kernel.json_field "allowed" (Kernel.json_bool guard.guard_allowed);
      Kernel.json_field "decision"
        (Kernel.json_string (if guard.guard_allowed then "allow" else "deny"));
      Kernel.json_field "reason" (Kernel.json_string guard.guard_reason);
      Kernel.json_field "requiredCommand" (Kernel.json_string guard.guard_required_command);
    ]
  ^ "\n"

let guard_write_json path = guard_write_result_json (guard_write path)

let stage_json name input output command =
  Kernel.json_obj
    [
      Kernel.json_field "name" (Kernel.json_string name);
      Kernel.json_field "input" (Kernel.json_string input);
      Kernel.json_field "output" (Kernel.json_string output);
      Kernel.json_field "command" (Kernel.json_string command);
    ]

let protocol_json () =
  Kernel.json_obj
    [
      Kernel.json_field "format" (Kernel.json_string format);
      Kernel.json_field "pipeline"
        (json_string_list [ "AI"; "PatchCandidate"; "Validator"; "Harness"; "Commit" ]);
      Kernel.json_field "stages"
        (Kernel.json_array
           (fun (name, input, output, command) -> stage_json name input output command)
           [
             ( "AI",
               "agent intent plus graph/query context",
               "patch candidate proposal",
               "protoss agent graph / protoss agent explain" );
             ( "PatchCandidate",
               "structured patch JSON",
               "reviewable patch candidate",
               "protoss patch review <patch.json>" );
             ( "Validator",
               "patch candidate and target store",
               "checked patch or diagnostic",
               "protoss patch check <store> <patch.json>" );
             ( "Harness",
               "checked patch and attached harness set",
               "harness pass/fail report",
               "reserved: protoss harness run <store>" );
             ( "Commit",
               "validated patch and passing harness report",
               "content-addressed patch audit",
               "protoss agent commit <store> <patch.json>" );
           ]);
      Kernel.json_field "mutationPolicy"
        (Kernel.json_obj
           [
             Kernel.json_field "directCanonicalWrites" (Kernel.json_string "forbidden");
             Kernel.json_field "guardCommand"
               (Kernel.json_string "protoss agent guard-write <path>");
             Kernel.json_field "commitCommand"
               (Kernel.json_string "protoss agent commit <store> <patch.json>");
           ]);
    ]
  ^ "\n"

let commit_patch_json store patch =
  let checked = Patch.check store patch in
  let result = Patch.describe_checked checked in
  let patch_ref = Patch.apply store patch in
  Kernel.json_obj
    [
      Kernel.json_field "format" (Kernel.json_string commit_format);
      Kernel.json_field "protocol" (Kernel.json_string format);
      Kernel.json_field "stage" (Kernel.json_string "Commit");
      Kernel.json_field "store" (Kernel.json_string store);
      Kernel.json_field "patch" (Kernel.json_string patch);
      Kernel.json_field "mutation" (Kernel.json_string "validated-patch");
      Kernel.json_field "harnessStatus" (Kernel.json_string "empty-harness-set");
      Kernel.json_field "directCanonicalWrites" (Kernel.json_bool false);
      Kernel.json_field "result" (Kernel.json_string result);
      Kernel.json_field "patchRef" (Kernel.json_string patch_ref);
      Kernel.json_field "canonicalWriteGuard"
        (String.trim (guard_write_json (Filename.concat store "program.canon")));
    ]
  ^ "\n"
