type write_guard = {
  guard_path : string;
  guard_allowed : bool;
  guard_reason : string;
  guard_required_command : string;
}

let format = "protoss-agent-protocol-v1"

let commit_format = "protoss-agent-commit-v1"

let guard_format = "protoss-agent-write-guard-v1"

let factor_format = "protoss-factor-identical-v1"

let candidate_comparison_format = "protoss-agent-candidate-comparison-v1"

let test_synthesis_format = "protoss-agent-test-synthesis-v1"

let migration_generation_format = "protoss-agent-migration-generation-v1"

let commit_command =
  "protoss agent commit <store> <patch.json> --harness <harness.pth>"

let json_string_list xs = Kernel.json_array Kernel.json_string xs

let sort_uniq_strings xs = List.sort_uniq String.compare xs

let contains haystack needle =
  let haystack_len = String.length haystack and needle_len = String.length needle in
  needle_len = 0
  ||
  let rec loop i =
    i + needle_len <= haystack_len
    && (String.sub haystack i needle_len = needle || loop (i + 1))
  in
  loop 0

let has_suffix suffix s =
  let suffix_len = String.length suffix and len = String.length s in
  len >= suffix_len && String.sub s (len - suffix_len) suffix_len = suffix

let normalize_path path =
  path |> String.lowercase_ascii |> String.map (function '\\' -> '/' | c -> c)

let path_has_segment path segment = contains ("/" ^ path ^ "/") ("/" ^ segment ^ "/")

let direct_canonical_reason path =
  let path = normalize_path path in
  if has_suffix "/program.canon" path || has_suffix "/program.graph.json" path then
    Some "program canonical artifacts are written only by validated patch/project commands"
  else if has_suffix ".ptc" path || has_suffix ".ptb" path then
    Some "canonical source artifacts are generated outputs, not direct agent write targets"
  else if
    List.exists
      (path_has_segment path)
      [
        "defs";
        "objects";
        "graphs";
        "types";
        "deps";
        "normal";
        "defids";
        "capability-scopes";
        "host-contracts";
      ]
  then Some "store internals are mutated only through validated patch/project commands"
  else if path_has_segment path "provenance" || path_has_segment path "patches" then
    Some "audit and provenance records are written only by patch commit"
  else if
    List.exists
      (fun suffix -> has_suffix suffix path)
      [ "/universe.root"; "/universe.root.content"; "/host.contract.json"; "/lock"; "/package" ]
  then Some "root, lock, package, and host-contract artifacts are generated by trusted commands"
  else None

let guard_write path =
  match direct_canonical_reason path with
  | Some reason ->
      {
        guard_path = path;
        guard_allowed = false;
        guard_reason = reason;
        guard_required_command = commit_command;
      }
  | None ->
      {
        guard_path = path;
        guard_allowed = true;
        guard_reason = "path is outside canonical/store internals";
        guard_required_command = "";
      }

let guard_write_allowed path = (guard_write path).guard_allowed

let guard_write_result_json guard =
  Kernel.json_obj
    [
      Kernel.json_field "format" (Kernel.json_string guard_format);
      Kernel.json_field "path" (Kernel.json_string guard.guard_path);
      Kernel.json_field "allowed" (Kernel.json_bool guard.guard_allowed);
      Kernel.json_field "decision"
        (Kernel.json_string (if guard.guard_allowed then "allow" else "deny"));
      Kernel.json_field "reason" (Kernel.json_string guard.guard_reason);
      Kernel.json_field "requiredCommand" (Kernel.json_string guard.guard_required_command);
    ]
  ^ "\n"

let guard_write_json path = guard_write_result_json (guard_write path)

let stage_json name input output command =
  Kernel.json_obj
    [
      Kernel.json_field "name" (Kernel.json_string name);
      Kernel.json_field "input" (Kernel.json_string input);
      Kernel.json_field "output" (Kernel.json_string output);
      Kernel.json_field "command" (Kernel.json_string command);
    ]

let protocol_json () =
  Kernel.json_obj
    [
      Kernel.json_field "format" (Kernel.json_string format);
      Kernel.json_field "pipeline"
        (json_string_list [ "AI"; "PatchCandidate"; "Validator"; "Harness"; "Commit" ]);
      Kernel.json_field "stages"
        (Kernel.json_array
           (fun (name, input, output, command) -> stage_json name input output command)
           [
             ( "AI",
               "agent intent plus graph/query context",
               "patch candidate proposal",
               "protoss agent graph / protoss agent explain" );
             ( "PatchCandidate",
               "structured patch JSON",
               "reviewable patch candidate",
               "protoss patch review <patch.json>" );
             ( "Validator",
               "patch candidate and target store",
               "checked patch or diagnostic",
               "protoss patch check <store> <patch.json>" );
             ( "Harness",
               "checked patch and attached harness set",
               "harness pass/fail report",
               "protoss harness run <store> <harness.pth>" );
             ( "Commit",
               "validated patch and passing harness report",
               "content-addressed patch audit",
               commit_command );
           ]);
      Kernel.json_field "mutationPolicy"
        (Kernel.json_obj
           [
             Kernel.json_field "directCanonicalWrites" (Kernel.json_string "forbidden");
             Kernel.json_field "guardCommand"
               (Kernel.json_string "protoss agent guard-write <path>");
             Kernel.json_field "commitCommand" (Kernel.json_string commit_command);
           ]);
    ]
  ^ "\n"

type factor_delete = {
  delete_name : string;
  delete_def_id : string;
  delete_representative : string;
  delete_deps : string list;
}

type factor_blocked = {
  blocked_name : string;
  blocked_def_id : string;
  blocked_representative : string;
  blocked_dependents : string list;
}

type factor_group = {
  group_def_id : string;
  group_representative : string;
  group_names : string list;
  group_deletes : factor_delete list;
  group_blocked : factor_blocked list;
}

type factor_plan = {
  factor_groups : factor_group list;
  factor_deletes : factor_delete list;
  factor_blocked : factor_blocked list;
}

let source_dependents defs name =
  defs
  |> List.filter (fun (d : Ast.def) ->
         not (String.equal d.name name)
         && List.exists (String.equal name) (Kernel.dependencies_of_defs defs d.name))
  |> List.map (fun (d : Ast.def) -> d.name)
  |> sort_uniq_strings

let duplicate_groups checked =
  let groups = Hashtbl.create (List.length checked.Kernel.defs) in
  List.iter
    (fun (d : Kernel.checked_def) ->
      let existing = Option.value (Hashtbl.find_opt groups d.Kernel.def_id) ~default:[] in
      Hashtbl.replace groups d.Kernel.def_id (d :: existing))
    checked.Kernel.defs;
  Hashtbl.fold
    (fun def_id defs acc ->
      let defs =
        List.sort
          (fun (a : Kernel.checked_def) (b : Kernel.checked_def) ->
            String.compare a.Kernel.def.name b.Kernel.def.name)
          defs
      in
      match defs with _ :: _ :: _ -> (def_id, defs) :: acc | _ -> acc)
    groups []
  |> List.sort (fun (a, _) (b, _) -> String.compare a b)

let factor_group checked (def_id, defs) =
  let source_defs = checked.Kernel.program.defs in
  let representative =
    match defs with
    | first :: _ -> first.Kernel.def.name
    | [] -> Kernel.fail "internal empty duplicate group"
  in
  let names = List.map (fun (d : Kernel.checked_def) -> d.Kernel.def.name) defs in
  let deletes, blocked =
    match defs with
    | [] | [ _ ] -> ([], [])
    | _representative :: duplicates ->
        duplicates
        |> List.fold_left
             (fun (deletes, blocked) (d : Kernel.checked_def) ->
               let dependents = source_dependents source_defs d.Kernel.def.name in
               if dependents = [] then
                 ( {
                     delete_name = d.Kernel.def.name;
                     delete_def_id = def_id;
                     delete_representative = representative;
                     delete_deps =
                       Kernel.dependencies_of_defs source_defs d.Kernel.def.name
                       |> sort_uniq_strings;
                   }
                   :: deletes,
                   blocked )
               else
                 ( deletes,
                   {
                     blocked_name = d.Kernel.def.name;
                     blocked_def_id = def_id;
                     blocked_representative = representative;
                     blocked_dependents = dependents;
                   }
                   :: blocked ))
             ([], [])
  in
  {
    group_def_id = def_id;
    group_representative = representative;
    group_names = names;
    group_deletes = List.rev deletes;
    group_blocked = List.rev blocked;
  }

let factor_identical_plan checked =
  let groups = duplicate_groups checked |> List.map (factor_group checked) in
  {
    factor_groups = groups;
    factor_deletes = List.concat_map (fun group -> group.group_deletes) groups;
    factor_blocked = List.concat_map (fun group -> group.group_blocked) groups;
  }

let factor_delete_op_json delete =
  Kernel.json_obj
    [
      Kernel.json_field "op" (Kernel.json_string "DeleteDef");
      Kernel.json_field "name" (Kernel.json_string delete.delete_name);
      Kernel.json_field "deps" (json_string_list delete.delete_deps);
    ]

let factor_patch_candidate_json plan =
  Kernel.json_obj
    [ Kernel.json_field "ops" (Kernel.json_array factor_delete_op_json plan.factor_deletes) ]

let factor_delete_json delete =
  Kernel.json_obj
    [
      Kernel.json_field "name" (Kernel.json_string delete.delete_name);
      Kernel.json_field "defId" (Kernel.json_string delete.delete_def_id);
      Kernel.json_field "representative" (Kernel.json_string delete.delete_representative);
      Kernel.json_field "deps" (json_string_list delete.delete_deps);
    ]

let factor_blocked_json blocked =
  Kernel.json_obj
    [
      Kernel.json_field "name" (Kernel.json_string blocked.blocked_name);
      Kernel.json_field "defId" (Kernel.json_string blocked.blocked_def_id);
      Kernel.json_field "representative" (Kernel.json_string blocked.blocked_representative);
      Kernel.json_field "dependents" (json_string_list blocked.blocked_dependents);
      Kernel.json_field "reason"
        (Kernel.json_string "source dependents must be rewritten before deletion");
    ]

let factor_group_json group =
  Kernel.json_obj
    [
      Kernel.json_field "defId" (Kernel.json_string group.group_def_id);
      Kernel.json_field "representative" (Kernel.json_string group.group_representative);
      Kernel.json_field "names" (json_string_list group.group_names);
      Kernel.json_field "safeDeletes" (Kernel.json_array factor_delete_json group.group_deletes);
      Kernel.json_field "blocked" (Kernel.json_array factor_blocked_json group.group_blocked);
    ]

let factor_identical_patch_json checked =
  factor_patch_candidate_json (factor_identical_plan checked) ^ "\n"

let factor_identical_json checked =
  let plan = factor_identical_plan checked in
  Kernel.json_obj
    [
      Kernel.json_field "format" (Kernel.json_string factor_format);
      Kernel.json_field "protocol" (Kernel.json_string format);
      Kernel.json_field "stage" (Kernel.json_string "PatchCandidate");
      Kernel.json_field "programHash" (Kernel.json_string (Kernel.hash_program checked));
      Kernel.json_field "duplicateGroups" (string_of_int (List.length plan.factor_groups));
      Kernel.json_field "safeDeleteCount" (string_of_int (List.length plan.factor_deletes));
      Kernel.json_field "blockedCount" (string_of_int (List.length plan.factor_blocked));
      Kernel.json_field "groups" (Kernel.json_array factor_group_json plan.factor_groups);
      Kernel.json_field "patchCandidate" (factor_patch_candidate_json plan);
      Kernel.json_field "validationCommand"
        (Kernel.json_string "protoss patch check <store> <patch.json>");
      Kernel.json_field "commitCommand" (Kernel.json_string commit_command);
    ]
  ^ "\n"

type candidate_check = {
  candidate_label : string;
  candidate_patch : string;
  candidate_valid : bool;
  candidate_result : string;
  candidate_program_hash : string;
  candidate_changes : int;
  candidate_diagnostic : string;
}

let check_candidate store label patch =
  try
    let checked = Patch.check store patch in
    {
      candidate_label = label;
      candidate_patch = patch;
      candidate_valid = true;
      candidate_result = Patch.describe_checked checked;
      candidate_program_hash = Kernel.hash_program checked.Patch.checked;
      candidate_changes = List.length checked.Patch.changes;
      candidate_diagnostic = "";
    }
  with Patch.Error msg ->
    {
      candidate_label = label;
      candidate_patch = patch;
      candidate_valid = false;
      candidate_result = "";
      candidate_program_hash = "";
      candidate_changes = 0;
      candidate_diagnostic = msg;
    }

let candidate_json candidate =
  Kernel.json_obj
    [
      Kernel.json_field "label" (Kernel.json_string candidate.candidate_label);
      Kernel.json_field "patch" (Kernel.json_string candidate.candidate_patch);
      Kernel.json_field "valid" (Kernel.json_bool candidate.candidate_valid);
      Kernel.json_field "result" (Kernel.json_string candidate.candidate_result);
      Kernel.json_field "programHash" (Kernel.json_string candidate.candidate_program_hash);
      Kernel.json_field "changes" (string_of_int candidate.candidate_changes);
      Kernel.json_field "diagnostic" (Kernel.json_string candidate.candidate_diagnostic);
    ]

let comparison_decision left right =
  match (left.candidate_valid, right.candidate_valid) with
  | true, false -> ("left", "left-valid-right-invalid", false)
  | false, true -> ("right", "right-valid-left-invalid", false)
  | false, false -> ("tie", "both-invalid", false)
  | true, true
    when String.equal left.candidate_program_hash right.candidate_program_hash ->
      ("tie", "same-program-hash", false)
  | true, true -> ("tie", "both-valid-distinct-results", true)

let compare_candidates_json store patch_left patch_right =
  let left = check_candidate store "left" patch_left in
  let right = check_candidate store "right" patch_right in
  let recommendation, reason, requires_harness = comparison_decision left right in
  Kernel.json_obj
    [
      Kernel.json_field "format" (Kernel.json_string candidate_comparison_format);
      Kernel.json_field "protocol" (Kernel.json_string format);
      Kernel.json_field "stage" (Kernel.json_string "Validator");
      Kernel.json_field "store" (Kernel.json_string store);
      Kernel.json_field "recommendation" (Kernel.json_string recommendation);
      Kernel.json_field "reason" (Kernel.json_string reason);
      Kernel.json_field "requiresHarness" (Kernel.json_bool requires_harness);
      Kernel.json_field "candidates" (Kernel.json_array candidate_json [ left; right ]);
    ]
  ^ "\n"

let harness_name name suffix =
  let b = Buffer.create (String.length name + String.length suffix + 1) in
  String.iter
    (function
      | 'a' .. 'z' | 'A' .. 'Z' | '0' .. '9' as c -> Buffer.add_char b c
      | _ -> Buffer.add_char b '_')
    name;
  Buffer.add_char b '_';
  Buffer.add_string b suffix;
  Buffer.contents b

let rec suggested_test_kind = function
  | Ast.TProcess _ -> "process-ledger"
  | Ast.TCmd _ -> "web-command"
  | Ast.TFun _ -> "example-call"
  | Ast.TForall (_, t) -> suggested_test_kind t
  | _ -> "normalization"

let suggested_harness_template name typ =
  match suggested_test_kind typ with
  | "process-ledger" -> "harness " ^ harness_name name "process" ^ " = scenario " ^ name
  | "example-call" -> "harness " ^ harness_name name "example" ^ " = example " ^ name ^ " (...)"
  | _ -> "harness " ^ harness_name name "normalizes" ^ " = unit " ^ name ^ " == <expected>"

let test_suggestion_json (d : Kernel.checked_def) =
  let type_canonical = Kernel.type_to_canonical d.Kernel.def.typ in
  Kernel.json_obj
    [
      Kernel.json_field "name" (Kernel.json_string d.def.name);
      Kernel.json_field "defId" (Kernel.json_string d.def_id);
      Kernel.json_field "typeCanonical" (Kernel.json_string type_canonical);
      Kernel.json_field "kind" (Kernel.json_string (suggested_test_kind d.def.typ));
      Kernel.json_field "harnessTemplate"
        (Kernel.json_string (suggested_harness_template d.def.name d.def.typ));
      Kernel.json_field "reason"
        (Kernel.json_string "definition is public to the checked program graph");
    ]

let synthesize_tests_json checked =
  let defs =
    checked.Kernel.defs
    |> List.sort
         (fun (a : Kernel.checked_def) (b : Kernel.checked_def) ->
           String.compare a.Kernel.def.name b.Kernel.def.name)
  in
  Kernel.json_obj
    [
      Kernel.json_field "format" (Kernel.json_string test_synthesis_format);
      Kernel.json_field "protocol" (Kernel.json_string format);
      Kernel.json_field "stage" (Kernel.json_string "Harness");
      Kernel.json_field "programHash" (Kernel.json_string (Kernel.hash_program checked));
      Kernel.json_field "suggestionCount" (string_of_int (List.length defs));
      Kernel.json_field "suggestions" (Kernel.json_array test_suggestion_json defs);
      Kernel.json_field "nextCommand"
        (Kernel.json_string "protoss harness run <store> <harness.pth>");
    ]
  ^ "\n"

let rec default_expr_source = function
  | Ast.TUnit -> Some "unit"
  | Ast.TBool -> Some "false"
  | Ast.TNat -> Some "0"
  | Ast.TString -> Some "\"\""
  | Ast.TList t -> Some ("(Nil " ^ Ast.string_of_typ t ^ ")")
  | Ast.TRecord fields ->
      let field_exprs =
        fields
        |> List.map (fun (name, typ) ->
               Option.map (fun expr -> "(" ^ name ^ " " ^ expr ^ ")") (default_expr_source typ))
      in
      if List.for_all Option.is_some field_exprs then
        Some
          ("(record "
          ^ String.concat " " (List.map (fun item -> Option.get item) field_exprs)
          ^ ")")
      else None
  | _ -> None

let rec migration_expr_for old_expr old_typ new_typ =
  if Ast.equal_typ old_typ new_typ then ([ "copy" ], old_expr)
  else
    match (old_typ, new_typ) with
    | Ast.TRecord old_fields, Ast.TRecord new_fields ->
        let planned =
          new_fields
          |> List.map (fun (name, typ) ->
                 let strategies, expr =
                   match List.assoc_opt name old_fields with
                   | Some old_typ ->
                       migration_expr_for ("(get " ^ old_expr ^ " " ^ name ^ ")") old_typ typ
                   | None -> (
                       match default_expr_source typ with
                       | Some expr -> ([ "default" ], expr)
                       | None -> ([ "manual" ], "unit"))
                 in
                 (name, strategies, expr))
        in
        let body =
          "(record "
          ^ String.concat " "
              (List.map (fun (name, _, expr) -> "(" ^ name ^ " " ^ expr ^ ")") planned)
          ^ ")"
        in
        ("nested" :: List.concat_map (fun (_, strategies, _) -> strategies) planned, body)
    | _ -> (
        match default_expr_source new_typ with
        | Some expr -> ([ "default" ], expr)
        | None -> ([ "manual" ], "unit"))

let migration_expr_source old_model new_model =
  let strategies, body =
    if Ast.equal_typ old_model new_model then ([ "copy" ], "old")
    else migration_expr_for "old" old_model new_model
  in
  ( "(lambda (old " ^ Ast.string_of_typ old_model ^ ") " ^ body ^ ")",
    sort_uniq_strings strategies )

let migration_patch_candidate old_model new_model expr =
  Kernel.json_obj
    [
      Kernel.json_field "ops"
        (Kernel.json_array
           (fun () ->
             Kernel.json_obj
               [
                 Kernel.json_field "op" (Kernel.json_string "AddDef");
                 Kernel.json_field "name" (Kernel.json_string "migrate_v1_v2");
                 Kernel.json_field "deps" (json_string_list []);
                 Kernel.json_field "type"
                   (Kernel.json_obj
                      [
                        Kernel.json_field "source"
                          (Kernel.json_string
                             (Ast.string_of_typ (Ast.TFun (old_model, new_model))));
                      ]);
                 Kernel.json_field "expr"
                   (Kernel.json_obj [ Kernel.json_field "source" (Kernel.json_string expr) ]);
               ])
           [ () ]);
    ]

let generate_migration_json old_store new_store =
  let old_checked = Store.load_program old_store |> Kernel.check_program in
  let new_checked = Store.load_program new_store |> Kernel.check_program in
  let old_contract = Web.check_contract old_checked in
  let new_contract = Web.check_contract new_checked in
  let required = not (Ast.equal_typ old_contract.Web.model_ty new_contract.Web.model_ty) in
  let expr, strategies =
    if required then migration_expr_source old_contract.model_ty new_contract.model_ty
    else ("", [])
  in
  Kernel.json_obj
    [
      Kernel.json_field "format" (Kernel.json_string migration_generation_format);
      Kernel.json_field "protocol" (Kernel.json_string format);
      Kernel.json_field "stage" (Kernel.json_string "PatchCandidate");
      Kernel.json_field "oldStore" (Kernel.json_string old_store);
      Kernel.json_field "newStore" (Kernel.json_string new_store);
      Kernel.json_field "oldModel" (Kernel.json_string (Ast.string_of_typ old_contract.model_ty));
      Kernel.json_field "newModel" (Kernel.json_string (Ast.string_of_typ new_contract.model_ty));
      Kernel.json_field "required" (Kernel.json_bool required);
      Kernel.json_field "migrationName" (Kernel.json_string "migrate_v1_v2");
      Kernel.json_field "strategies" (json_string_list strategies);
      Kernel.json_field "expr" (Kernel.json_string expr);
      Kernel.json_field "patchCandidate"
        (if required then migration_patch_candidate old_contract.model_ty new_contract.model_ty expr
         else Kernel.json_obj [ Kernel.json_field "ops" (Kernel.json_array (fun x -> x) []) ]);
      Kernel.json_field "validationCommand"
        (Kernel.json_string "protoss patch check <old-store> <migration.patch.json>");
    ]
  ^ "\n"

type harness_validation = {
  harness_path : string;
  harness_report : string;
  harness_status : string;
}

let json_string_field name obj =
  match Json.field name obj with
  | Some value -> (
      match Json.string value with
      | Some s -> s
      | None -> Kernel.fail ("harness report field must be string: " ^ name))
  | None -> Kernel.fail ("harness report missing field: " ^ name)

let harness_status report =
  try json_string_field "status" (Json.parse report) with
  | Json.Error msg -> Kernel.fail ("invalid harness report JSON: " ^ msg)

let validate_harness checked path =
  let report = Harness.run_json checked ~source:path (Patch.read_file path) in
  { harness_path = path; harness_report = report; harness_status = harness_status report }

let harness_report_json validation =
  let report = String.trim validation.harness_report in
  ignore (Json.parse report);
  report

let validate_harnesses checked = function
  | [] ->
      Kernel.fail
        "HARNESS001 HarnessRegression: agent commit requires at least one attached harness"
  | harnesses ->
      let validations = List.map (validate_harness checked) harnesses in
      (match
         List.find_opt
           (fun validation -> not (String.equal validation.harness_status "pass"))
           validations
       with
      | Some failed ->
          Kernel.fail
            ("HARNESS001 HarnessRegression: attached harness failed: "
            ^ failed.harness_path ^ "\n" ^ String.trim failed.harness_report)
      | None -> validations)

let commit_patch_json ?(harnesses = []) store patch =
  let checked = Patch.check store patch in
  let result = Patch.describe_checked checked in
  let harness_validations = validate_harnesses checked.Patch.checked harnesses in
  let patch_ref = Patch.apply store patch in
  Kernel.json_obj
    [
      Kernel.json_field "format" (Kernel.json_string commit_format);
      Kernel.json_field "protocol" (Kernel.json_string format);
      Kernel.json_field "stage" (Kernel.json_string "Commit");
      Kernel.json_field "store" (Kernel.json_string store);
      Kernel.json_field "patch" (Kernel.json_string patch);
      Kernel.json_field "mutation" (Kernel.json_string "validated-patch");
      Kernel.json_field "harnessStatus" (Kernel.json_string "pass");
      Kernel.json_field "harnessCount" (string_of_int (List.length harness_validations));
      Kernel.json_field "harnessReports"
        (Kernel.json_array harness_report_json harness_validations);
      Kernel.json_field "directCanonicalWrites" (Kernel.json_bool false);
      Kernel.json_field "result" (Kernel.json_string result);
      Kernel.json_field "patchRef" (Kernel.json_string patch_ref);
      Kernel.json_field "canonicalWriteGuard"
        (String.trim (guard_write_json (Filename.concat store "program.canon")));
    ]
  ^ "\n"
